# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the compute configuration')),
                ('desc', models.CharField(max_length=256, verbose_name='Description of the engine')),
                ('template', models.TextField(verbose_name='Compute template')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ComputeEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the compute engine')),
                ('desc', models.CharField(max_length=256, verbose_name='Description of the engine')),
                ('conf', models.TextField(verbose_name='Configuration of the compute engine')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.AddField(
            model_name='computeconfiguration',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.ComputeEngine', verbose_name='Engine to be used'),
        ),
    ]
