# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_auto_20170106_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatawarehouseComputeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the compute configuration')),
                ('desc', models.TextField(verbose_name='Description of the configuration')),
                ('layer', models.IntegerField(choices=[(0, 'Flexible Dimension Extraction Layer'), (1, 'Fixed Dimension Extraction Layer'), (2, 'Data Aggregation Layer')], verbose_name='The layer of the configuration')),
                ('template', models.TextField(verbose_name='Compute template')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.ComputeEngine', verbose_name='Engine to be used')),
            ],
        ),
        migrations.RemoveField(
            model_name='computeconfiguration',
            name='engine',
        ),
        migrations.DeleteModel(
            name='ComputeConfiguration',
        ),
    ]
