# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_auto_20170106_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageEnigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the storage')),
                ('desc', models.TextField(verbose_name='Description of the storage')),
                ('stype', models.SmallIntegerField(choices=[(0, 'Context Storage'), (1, 'Result Storage')], verbose_name='Storage type')),
                ('conf', models.TextField(verbose_name='Configuration of the storage')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.AddField(
            model_name='datawarehousecomputeconfiguration',
            name='output',
            field=models.TextField(blank=True, default='', null=True, verbose_name='The output configuration'),
        ),
        migrations.AlterField(
            model_name='datawarehousecomputeconfiguration',
            name='layer',
            field=models.SmallIntegerField(choices=[(0, 'Base Extraction Layer'), (1, 'Flexible Dimension Extraction Layer'), (0, 'Flexible Dimension Extraction Layer'), (0, 'Flexible Dimension Extraction Layer'), (1, 'Flexible Dimension Extraction Layer'), (2, 'Fixed Dimension Extraction Layer'), (2, 'Data Aggregation Layer')], verbose_name='The layer of the configuration'),
        ),
    ]
