# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20170109_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the Report')),
                ('desc', models.TextField(verbose_name='Help text of the report')),
                ('template', models.TextField(verbose_name='Compute template')),
                ('output', models.TextField(verbose_name='The output configuration')),
                ('visualization', models.TextField(verbose_name='The visualization configuration')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.AddField(
            model_name='computeengine',
            name='ctype',
            field=models.SmallIntegerField(choices=[(0, 'Hive'), (1, 'Presto')], default=0, verbose_name='Compute Engine Type'),
        ),
        migrations.AlterField(
            model_name='datawarehousecomputeconfiguration',
            name='layer',
            field=models.SmallIntegerField(choices=[(0, 'Base Conceptions Extraction Layer'), (1, 'Flexible Dimension Extraction Layer'), (2, 'Fixed Dimension Extraction Layer'), (3, 'Data Aggregation Layer')], verbose_name='The layer of the configuration'),
        ),
        migrations.AddField(
            model_name='report',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.ComputeEngine', verbose_name='Engine to be used'),
        ),
    ]
