# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_auto_20170109_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the Report unit')),
                ('refer', models.CharField(max_length=128, verbose_name='Refer name of the report unit')),
                ('desc', models.TextField(verbose_name='Help text of the report')),
                ('template', models.TextField(verbose_name='Compute template')),
                ('output', models.TextField(verbose_name='The output configuration')),
                ('visualization', models.TextField(verbose_name='The visualization configuration')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.ComputeEngine', verbose_name='Engine to be used')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='engine',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
