# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20170110_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageenigne',
            name='setype',
            field=models.SmallIntegerField(choices=[(0, 'Elasticsearch'), (1, 'Redis'), (2, 'MySQL')], default=0, verbose_name='Storage engine type'),
        ),
        migrations.AlterField(
            model_name='storageenigne',
            name='stype',
            field=models.SmallIntegerField(choices=[(0, 'Context Storage'), (1, 'Result Storage')], default=0, verbose_name='Storage type'),
        ),
    ]
