# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_auto_20170110_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeengine',
            name='ctype',
            field=models.CharField(choices=[('HIVE', 'Hive'), ('PRESTO', 'Presto')], default='HIVE', max_length=32, verbose_name='Compute Engine Type'),
        ),
        migrations.AlterField(
            model_name='storageenigne',
            name='setype',
            field=models.SmallIntegerField(choices=[('ELASTICSEARCH', 'Elasticsearch'), ('REDIS', 'Redis'), ('MYSQL', 'MySQL')], default='ELASTICSEARCH', max_length=32, verbose_name='Storage engine type'),
        ),
        migrations.AlterField(
            model_name='storageenigne',
            name='stype',
            field=models.CharField(choices=[('CONTEXT', 'Context Storage'), ('RESULT', 'Result Storage')], default='CONTEXT', max_length=32, verbose_name='Storage type'),
        ),
    ]
