# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_auto_20170110_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageenigne',
            name='setype',
            field=models.CharField(choices=[('ELASTICSEARCH', 'Elasticsearch'), ('REDIS', 'Redis'), ('MYSQL', 'MySQL')], default='ELASTICSEARCH', max_length=32, verbose_name='Storage engine type'),
        ),
    ]
