# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='APP ID')),
                ('name', models.CharField(max_length=128, verbose_name='APP name')),
                ('key', models.CharField(max_length=128, verbose_name='APP Key')),
                ('secret', models.CharField(max_length=128, verbose_name='APP Secret')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
    ]
